### ISSUE TITLE
How can I let users from any mastodon server sign in?

### ISSUE THREAD

**Issue by gka** [openwebtech/passport-mastodon#1]
Right now it seems that only users from *one specific* Mastodon can sign in using passport-mastodon (the domain I have to configure).

Or is there a way that users from *any* instance can be allowed to sign in?

**Comment by dsuket** [comment]
@gka  Sorry, this repository is no longer maintained.But you can customize by fork this.

This plugin bases from [passport-oauth2](https://github.com/jaredhanson/passport-oauth2), domain is provided by constructor arguments.
https://github.com/techfeed/passport-mastodon/blob/master/lib/strategy.js#L8

You may be able to dynamic change authorizationURL and tokenURL. Please refer passport-oauth2 for detail.

**Comment by gka** [comment]
thanks. I also figured it out already. asking users to enter a mastodon domain now and then creating the "app" automatically via mastodon api on-the-fly.
